/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SpecialAssistanceRouteImport } from './routes/special-assistance'
import { Route as SeatSelectionRouteImport } from './routes/seat-selection'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrebookMealRouteImport } from './routes/prebook-meal'
import { Route as PrebookBaggageRouteImport } from './routes/prebook-baggage'
import { Route as GiftCardRouteImport } from './routes/gift-card'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as IndexRouteImport } from './routes/index'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialAssistanceRoute = SpecialAssistanceRouteImport.update({
  id: '/special-assistance',
  path: '/special-assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatSelectionRoute = SeatSelectionRouteImport.update({
  id: '/seat-selection',
  path: '/seat-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrebookMealRoute = PrebookMealRouteImport.update({
  id: '/prebook-meal',
  path: '/prebook-meal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrebookBaggageRoute = PrebookBaggageRouteImport.update({
  id: '/prebook-baggage',
  path: '/prebook-baggage',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardRoute = GiftCardRouteImport.update({
  id: '/gift-card',
  path: '/gift-card',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/checkin': typeof CheckinRoute
  '/gift-card': typeof GiftCardRoute
  '/prebook-baggage': typeof PrebookBaggageRoute
  '/prebook-meal': typeof PrebookMealRoute
  '/search': typeof SearchRoute
  '/seat-selection': typeof SeatSelectionRoute
  '/special-assistance': typeof SpecialAssistanceRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/checkin': typeof CheckinRoute
  '/gift-card': typeof GiftCardRoute
  '/prebook-baggage': typeof PrebookBaggageRoute
  '/prebook-meal': typeof PrebookMealRoute
  '/search': typeof SearchRoute
  '/seat-selection': typeof SeatSelectionRoute
  '/special-assistance': typeof SpecialAssistanceRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/checkin': typeof CheckinRoute
  '/gift-card': typeof GiftCardRoute
  '/prebook-baggage': typeof PrebookBaggageRoute
  '/prebook-meal': typeof PrebookMealRoute
  '/search': typeof SearchRoute
  '/seat-selection': typeof SeatSelectionRoute
  '/special-assistance': typeof SpecialAssistanceRoute
  '/status': typeof StatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awards'
    | '/checkin'
    | '/gift-card'
    | '/prebook-baggage'
    | '/prebook-meal'
    | '/search'
    | '/seat-selection'
    | '/special-assistance'
    | '/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/checkin'
    | '/gift-card'
    | '/prebook-baggage'
    | '/prebook-meal'
    | '/search'
    | '/seat-selection'
    | '/special-assistance'
    | '/status'
  id:
    | '__root__'
    | '/'
    | '/awards'
    | '/checkin'
    | '/gift-card'
    | '/prebook-baggage'
    | '/prebook-meal'
    | '/search'
    | '/seat-selection'
    | '/special-assistance'
    | '/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwardsRoute: typeof AwardsRoute
  CheckinRoute: typeof CheckinRoute
  GiftCardRoute: typeof GiftCardRoute
  PrebookBaggageRoute: typeof PrebookBaggageRoute
  PrebookMealRoute: typeof PrebookMealRoute
  SearchRoute: typeof SearchRoute
  SeatSelectionRoute: typeof SeatSelectionRoute
  SpecialAssistanceRoute: typeof SpecialAssistanceRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-assistance': {
      id: '/special-assistance'
      path: '/special-assistance'
      fullPath: '/special-assistance'
      preLoaderRoute: typeof SpecialAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seat-selection': {
      id: '/seat-selection'
      path: '/seat-selection'
      fullPath: '/seat-selection'
      preLoaderRoute: typeof SeatSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prebook-meal': {
      id: '/prebook-meal'
      path: '/prebook-meal'
      fullPath: '/prebook-meal'
      preLoaderRoute: typeof PrebookMealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prebook-baggage': {
      id: '/prebook-baggage'
      path: '/prebook-baggage'
      fullPath: '/prebook-baggage'
      preLoaderRoute: typeof PrebookBaggageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-card': {
      id: '/gift-card'
      path: '/gift-card'
      fullPath: '/gift-card'
      preLoaderRoute: typeof GiftCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwardsRoute: AwardsRoute,
  CheckinRoute: CheckinRoute,
  GiftCardRoute: GiftCardRoute,
  PrebookBaggageRoute: PrebookBaggageRoute,
  PrebookMealRoute: PrebookMealRoute,
  SearchRoute: SearchRoute,
  SeatSelectionRoute: SeatSelectionRoute,
  SpecialAssistanceRoute: SpecialAssistanceRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
